### ISSUE TITLE
netwerk component leggertool vertoont bugs bij de berekening van Marken

### ISSUE THREAD

**Issue by jelledijkema** [jelledijkema/legger#39]
De netwerk component vertoon bugs bij Marken. Het lijkt wel of het begin gemaal niet gevonden wordt als startpunt, en de berekende profielvarianten die de tool wel goed weergeeft zien er in de lengedoorsnede grafiek "hoogte mbt waterlijn" funky uit

**Comment by bastiaan-roos** [comment]
Dat het netwerk niet klopt ligt aan de richting van enkele lijn elementen (er wordt wel opgemerkt dat de stroomingsrichting 'reversed' is door de debieten inlees en koppel tool), maar dit lijkt niet te worden meegenomen door de netwerktool.
 
Het funcky verloop komt doordat er vanaf één punt meerdere takken lopen (en die worden door elkaar getekend).

IK zal zorgen dat de netwerktool rekening gaat houden met 'reversed' (als snelle fix kan je de richtring omdraaien). 
Daarmee krijg je ook veel minder punten waar meerdere takken samenkomen (over een goede (interface) oplossing hiervoor moet ik nog even nadenken).

**Comment by bastiaan-roos** [comment]
fixed b16714161c475356b0ce413e85146498582dabd5
